export type CheckItem = { id: string; text: string };
export type Section = {
  day: string;
  title: string;
  tag: string;
  items: CheckItem[];
};
export type Week = { week: number; title: string; goal: string; sections: Section[] };

export const weeks: Week[] = [
  {
    week: 1,
    title: "Golang Foundation",
    goal: "Understand Go's core principles, syntax, and concurrency model. Build three small CLI tools.",
    sections: [
      {
        day: "Day 1",
        title: "Go Syntax & Core Concepts",
        tag: "2.5 hrs",
        items: [
          { id: "d1-1", text: "Complete Go tour sections (packages, variables, functions, control flow)" },
          { id: "d1-2", text: "Understand error handling pattern (if err != nil)" },
          { id: "d1-3", text: "Build: CLI calculator — go run main.go 10 5 add outputs 15" },
          { id: "d1-4", text: "Handle division by zero with Go's error pattern" },
          { id: "d1-5", text: "Commit: feat: day1-calculator-cli" },
        ],
      },
      {
        day: "Day 2",
        title: "Structs, Methods, Interfaces",
        tag: "2.5 hrs",
        items: [
          { id: "d2-1", text: "Study Go tour: Methods and Interfaces sections" },
          { id: "d2-2", text: "Understand receiver syntax (mental shift from JS)" },
          { id: "d2-3", text: "Build: Bank account system with Deposit, Withdraw, GetBalance, GetHistory" },
          { id: "d2-4", text: "Define Transaction interface implemented by Deposit and Withdraw" },
          { id: "d2-5", text: "Add validation: no overdraft, amounts > 0" },
          { id: "d2-6", text: "Commit: feat: day2-bank-account-system" },
        ],
      },
      {
        day: "Day 3",
        title: "Goroutines & Channels",
        tag: "3 hrs — Critical",
        items: [
          { id: "d3-1", text: "Study Go tour: Goroutines and Channels sections" },
          { id: "d3-2", text: "Watch: 'Go Concurrency Patterns' by Rob Pike (15 min)" },
          { id: "d3-3", text: "Goroutines / channels no longer feel like magic" },
          { id: "d3-4", text: "Build: Concurrent URL fetcher — 5+ URLs concurrently via goroutines + channels" },
          { id: "d3-5", text: "Simulate 2-second timeout per request" },
          { id: "d3-6", text: "Read: 'Concurrency is not Parallelism' by Rob Pike" },
          { id: "d3-7", text: "Commit: feat: day3-concurrent-url-fetcher" },
        ],
      },
      {
        day: "Day 4",
        title: "File I/O & Data Persistence",
        tag: "2.5 hrs",
        items: [
          { id: "d4-1", text: "Study packages: os, io, bufio, encoding/json" },
          { id: "d4-2", text: "Understand JSON marshaling (json.Marshal / json.Unmarshal)" },
          { id: "d4-3", text: "Build: Task manager with JSON persistence across runs" },
          { id: "d4-4", text: "Implement SaveAccount and LoadAccount with proper error handling" },
          { id: "d4-5", text: "Handle missing files gracefully" },
          { id: "d4-6", text: "Commit: feat: day4-json-persistence" },
        ],
      },
      {
        day: "Day 5",
        title: "HTTP Servers & REST APIs",
        tag: "3 hrs — Most Practical",
        items: [
          { id: "d5-1", text: "Study net/http: Server, HandleFunc, ListenAndServe" },
          { id: "d5-2", text: "Build: REST API for bank — GET/POST /accounts, deposit, withdraw" },
          { id: "d5-3", text: "All responses as JSON with proper status codes (200, 400, 404, 500)" },
          { id: "d5-4", text: "Server runs on localhost:8080 and tested with curl/Postman" },
          { id: "d5-5", text: "Proper error responses (invalid account, insufficient funds)" },
          { id: "d5-6", text: "Commit: feat: day5-rest-api-server" },
        ],
      },
      {
        day: "Day 6",
        title: "Testing & Error Handling",
        tag: "2.5 hrs",
        items: [
          { id: "d6-1", text: "Study: *testing.T, table-driven tests, custom error types" },
          { id: "d6-2", text: "Understand panic() vs error returns (idiomatic: error returns)" },
          { id: "d6-3", text: "Write 10+ test cases for bank API (unit + integration)" },
          { id: "d6-4", text: "Run: go test ./... -v — all pass" },
          { id: "d6-5", text: "Error cases (insufficient funds, invalid input) well-covered" },
          { id: "d6-6", text: "Commit: feat: day6-comprehensive-testing" },
        ],
      },
      {
        day: "Day 7",
        title: "Refactor & Polish",
        tag: "2 hrs",
        items: [
          { id: "d7-1", text: "Refactor bank API — organize into logical packages" },
          { id: "d7-2", text: "Add comments to all exported functions (Go doc standard)" },
          { id: "d7-3", text: "Run go vet and go fmt — no issues" },
          { id: "d7-4", text: "Create Makefile with build, test, run targets" },
          { id: "d7-5", text: "Write README.md with API documentation" },
          { id: "d7-6", text: "Week 1 checkpoint: 3 projects complete, goroutines comfortable" },
          { id: "d7-7", text: "Commit: refactor: day7-code-organization" },
        ],
      },
    ],
  },
  {
    week: 2,
    title: "Go Deepening + Applied AI Introduction",
    goal: "Master Go fundamentals enough to build production services. Begin Applied AI integration projects.",
    sections: [
      {
        day: "Day 8",
        title: "Databases & SQL",
        tag: "3 hrs",
        items: [
          { id: "d8-1", text: "Study: database/sql, drivers (sqlite/postgres), prepared statements" },
          { id: "d8-2", text: "Understand connection pools and query scanning" },
          { id: "d8-3", text: "Build: Upgrade bank API with SQLite/PostgreSQL persistence" },
          { id: "d8-4", text: "Create repository package abstracting DB operations (CRUD)" },
          { id: "d8-5", text: "Accounts persist across server restarts" },
          { id: "d8-6", text: "No SQL injection vulnerabilities (prepared statements)" },
          { id: "d8-7", text: "Commit: feat: day8-database-integration" },
        ],
      },
      {
        day: "Day 9",
        title: "Middleware, Logging, Error Handling",
        tag: "2.5 hrs",
        items: [
          { id: "d9-1", text: "Study: middleware pattern, slog (Go 1.21+), graceful shutdown" },
          { id: "d9-2", text: "Implement: request logging middleware (method, path, status, duration)" },
          { id: "d9-3", text: "Implement: request ID middleware for tracing" },
          { id: "d9-4", text: "Implement: simple token authentication (401 without token)" },
          { id: "d9-5", text: "Implement: panic recovery middleware" },
          { id: "d9-6", text: "Commit: feat: day9-middleware-logging" },
        ],
      },
      {
        day: "Day 10",
        title: "Applied AI — LLM Integration",
        tag: "2.5 hrs",
        items: [
          { id: "d10-1", text: "Study: LLM basics, prompt engineering, temperature/max_tokens/top_p" },
          { id: "d10-2", text: "Understand cost implications and rate limiting" },
          { id: "d10-3", text: "Set up API keys in environment variables (never hardcode)" },
          { id: "d10-4", text: "Build: Go CLI that calls Claude/OpenAI — accept prompt, return response" },
          { id: "d10-5", text: "Track token usage and estimated cost per call" },
          { id: "d10-6", text: "Commit: feat: day10-go-llm-integration" },
        ],
      },
      {
        day: "Day 11",
        title: "Prompt Engineering & RAG Basics",
        tag: "2.5 hrs",
        items: [
          { id: "d11-1", text: "Study: system prompts, few-shot, chain-of-thought, temperature tuning" },
          { id: "d11-2", text: "Understand RAG: query → retrieve docs → augment prompt → generate" },
          { id: "d11-3", text: "Build: Document Q&A — load markdown, keyword retrieval, context injection" },
          { id: "d11-4", text: "Test same question with / without system prompt (quality diff)" },
          { id: "d11-5", text: "Context injection visibly reduces hallucination" },
          { id: "d11-6", text: "Commit: feat: day11-document-qa-rag" },
        ],
      },
      {
        day: "Day 12",
        title: "Building an AI-Powered Service",
        tag: "3 hrs",
        items: [
          { id: "d12-1", text: "Study: multi-turn conversations, stateless vs stateful APIs, function calling" },
          { id: "d12-2", text: "Build: AI code reviewer — submit Go code, get review (correctness/perf/style)" },
          { id: "d12-3", text: "Multi-turn: follow-up questions supported" },
          { id: "d12-4", text: "Cache review results for identical code (cost optimization)" },
          { id: "d12-5", text: "Commit: feat: day12-code-reviewer-ai" },
        ],
      },
      {
        day: "Day 13",
        title: "Integrating AI into Bank API",
        tag: "3 hrs — Capstone",
        items: [
          { id: "d13-1", text: "Add POST /accounts/:id/advice — AI spending advice from transaction history" },
          { id: "d13-2", text: "Add POST /budgets/:id/analyze — AI budget pattern analysis" },
          { id: "d13-3", text: "Add GET /accounts/:id/summary — AI natural language account summary" },
          { id: "d13-4", text: "Cache AI results (don't repeat same analysis within 1 hour)" },
          { id: "d13-5", text: "Graceful degradation — core API works even if AI API fails" },
          { id: "d13-6", text: "Commit: feat: day13-bankapi-ai-integration" },
        ],
      },
      {
        day: "Day 14",
        title: "Testing & Deployment",
        tag: "2.5 hrs",
        items: [
          { id: "d14-1", text: "Study: mocking HTTP calls to AI APIs, evaluation patterns for prompts" },
          { id: "d14-2", text: "Write tests with MockAIClient returning canned responses" },
          { id: "d14-3", text: "Create multi-stage Dockerfile (golang builder → alpine runtime)" },
          { id: "d14-4", text: "Docker image builds and runs successfully" },
          { id: "d14-5", text: "Week 2 checkpoint: bank API + AI working, DB persisted, deployable" },
          { id: "d14-6", text: "Commit: feat: day14-test-mocks-docker" },
        ],
      },
    ],
  },
  {
    week: 3,
    title: "Advanced Patterns & Portfolio Projects",
    goal: "Build two standalone portfolio projects demonstrating mastery: pure-Go backend service + AI-integrated application.",
    sections: [
      {
        day: "Days 15–17",
        title: "Portfolio Project #1 — Task Queue Service",
        tag: "3 days × 3 hrs",
        items: [
          { id: "d15-1", text: "Day 15: Design schema, core queue logic (enqueue, dequeue, persistence)" },
          { id: "d15-2", text: "Day 16: HTTP handlers, background goroutine workers, retry with backoff" },
          { id: "d15-3", text: "Day 17: Tests, Dockerfile, README with curl examples" },
          { id: "d15-4", text: "POST /tasks and GET /tasks/:id endpoints work" },
          { id: "d15-5", text: "Workers process tasks concurrently via channels" },
          { id: "d15-6", text: "Failed tasks retry with exponential backoff" },
          { id: "d15-7", text: "Graceful shutdown: signal.NotifyContext catches SIGTERM" },
          { id: "d15-8", text: "Database records all task state transitions" },
          { id: "d15-9", text: "Commit: feat: day15-17-task-queue-service" },
        ],
      },
      {
        day: "Days 18–21",
        title: "Portfolio Project #2 — AI Content Engine",
        tag: "4 days × 2.5 hrs",
        items: [
          { id: "d18-1", text: "Day 18: Setup, DB schema, core AI client, prompt templates" },
          { id: "d18-2", text: "Day 19: Blog generator, caption generator, code doc generator" },
          { id: "d18-3", text: "Day 19: Sentiment analysis, categorization, key point extraction" },
          { id: "d18-4", text: "Day 20: Batch processing (10+ items), usage tracking, caching, tests" },
          { id: "d18-5", text: "Day 21: Docker, documentation, example curl scripts, README" },
          { id: "d18-6", text: "Multiple generation types work reliably" },
          { id: "d18-7", text: "Cost tracking is accurate" },
          { id: "d18-8", text: "Caching reduces redundant API calls" },
          { id: "d18-9", text: "Commit: feat: day18-21-ai-content-engine" },
        ],
      },
    ],
  },
  {
    week: 4,
    title: "Polish, Integration & Final Capstone",
    goal: "Build the final capstone combining everything: Go backend + task queue + AI integration. Polish portfolio.",
    sections: [
      {
        day: "Days 22–24",
        title: "Capstone — AI Personal Finance Assistant",
        tag: "3 days × 3 hrs",
        items: [
          { id: "d22-1", text: "Day 22: Full DB schema (accounts, transactions, categories, budgets)" },
          { id: "d22-2", text: "Day 23: AI analyzers, advisors, background jobs, caching" },
          { id: "d22-3", text: "Day 24: Tests, documentation, example workflows, Docker" },
          { id: "d22-4", text: "Core banking: create account, deposit, withdraw, view history" },
          { id: "d22-5", text: "AI spending pattern analysis — 'You spent 30% more on dining'" },
          { id: "d22-6", text: "Anomaly detection — 'This $400 charge is unusual'" },
          { id: "d22-7", text: "CSV import background job works" },
          { id: "d22-8", text: "Full test coverage (unit + integration)" },
          { id: "d22-9", text: "Commit: feat: day22-24-personal-finance-ai-capstone" },
        ],
      },
      {
        day: "Day 25",
        title: "Applied AI Course Completion",
        tag: "2.5 hrs",
        items: [
          { id: "d25-1", text: "Complete all remaining AI course modules" },
          { id: "d25-2", text: "Study: evaluation patterns, user feedback loops, cost optimization" },
          { id: "d25-3", text: "Add evaluation framework to AI Content Engine or Finance Assistant" },
          { id: "d25-4", text: "A/B test different prompt variations, track accuracy" },
          { id: "d25-5", text: "Commit: feat: day25-ai-evaluation-framework" },
        ],
      },
      {
        day: "Day 26",
        title: "Code Quality & Optimization",
        tag: "2.5 hrs",
        items: [
          { id: "d26-1", text: "Run go vet, go fmt, gofmt on all projects — clean" },
          { id: "d26-2", text: "Add input validation to all endpoints" },
          { id: "d26-3", text: "Security review: no SQL injection, proper auth, no exposed secrets" },
          { id: "d26-4", text: "Optimize DB queries (add indexes, review slow paths)" },
          { id: "d26-5", text: "Write benchmarks for critical paths (BenchmarkWithdraw etc.)" },
          { id: "d26-6", text: "Add rate limiting on AI API calls" },
          { id: "d26-7", text: "Commit: refactor: day26-code-quality-optimization" },
        ],
      },
      {
        day: "Day 27",
        title: "Documentation & Deployment",
        tag: "2.5 hrs",
        items: [
          { id: "d27-1", text: "Write comprehensive README for each of 3 major projects" },
          { id: "d27-2", text: "Add architecture docs: design decisions, scalability considerations" },
          { id: "d27-3", text: "Document all API endpoints with request/response examples" },
          { id: "d27-4", text: "All projects deployable (Docker verified locally)" },
          { id: "d27-5", text: "Commit: docs: day27-comprehensive-documentation" },
        ],
      },
      {
        day: "Day 28",
        title: "GitHub Portfolio Polish",
        tag: "2 hrs",
        items: [
          { id: "d28-1", text: "Update GitHub bio: 'Go backend engineer + AI integration specialist'" },
          { id: "d28-2", text: "Pin 3 best projects with updated READMEs and badges" },
          { id: "d28-3", text: "Ensure all commit messages are meaningful (no 'fix' or 'update')" },
          { id: "d28-4", text: "Verify no secrets in public repo history" },
          { id: "d28-5", text: "Commit: chore: day28-github-portfolio-polish" },
        ],
      },
      {
        day: "Day 29",
        title: "Reflection & Knowledge Synthesis",
        tag: "1.5 hrs",
        items: [
          { id: "d29-1", text: "Write blog / personal doc: '30 Days: From JavaScript to Go & AI'" },
          { id: "d29-2", text: "Document: hardest concepts, key insights, what you'd do differently" },
          { id: "d29-3", text: "Create learning roadmap: what to learn next (gRPC, GraphQL, K8s)?" },
          { id: "d29-4", text: "Commit: docs: day29-learning-reflection" },
        ],
      },
      {
        day: "Day 30",
        title: "Final Integration Test & Next Steps",
        tag: "1.5 hrs",
        items: [
          { id: "d30-1", text: "Fresh clone all repos — go mod download, go build, go test ./... -v" },
          { id: "d30-2", text: "All projects start and endpoints respond correctly" },
          { id: "d30-3", text: "Write summary: 'What I Built in 30 Days' (skills + metrics)" },
          { id: "d30-4", text: "(Optional) Record 5-min video walkthrough of favorite project" },
          { id: "d30-5", text: "Commit: chore: day30-final-integration-complete" },
          { id: "d30-6", text: "Tag release: git tag -a v1.0 -m '30-day learning journey complete'" },
          { id: "d30-7", text: "git push origin --all && git push origin --tags" },
        ],
      },
    ],
  },
];
